"""Add thread_external_id to ThreadOrm

Revision ID: 75bbee0df035
Revises: 0e5142161cc1
Create Date: 2025-03-02 18:51:44.498736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bbee0df035'
down_revision: Union[str, None] = '0e5142161cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('thread_external_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'thread_external_id')
    # ### end Alembic commands ###
